name: First Pipeline
on: push
jobs:
  great:
    runs-on: ubuntu-latest
    steps:
      - name: Before checkout
        run: ls -la
      - name: Checkout code
        run: actions/checkout@v4
      - name: After checkout
        run: ls -la
        
