name: First Pipeline
on: push
jobs:
  great:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from First Pipeline!"
      - name: Show the machine
        run: |
          whoami
          uname -a
          pwd
        
